// Copyright © The Daybrite Project
// SPDX-License-Identifier: MPL-2.0

//! `day clean` — remove every build artifact a project accumulates: the CLI's own outputs
//! (`build/`), cargo's bare-invocation `target/`, and the generated outputs inside the
//! platform scaffolds (gradle's caches and build dirs, hvigor's, SwiftPM's local scratch).
//!
//! The list below is the scaffold `.gitignore`s, made executable: everything here is declared
//! generated by `day new`'s ignore rules, and nothing here is source, IDE state
//! (`xcuserdata/`, `DerivedData/`), or machine-local config (`local.properties`,
//! `.cargo/config.toml`) — those survive a clean.

use std::path::Path;

use crate::meta::Project;
use crate::ops::status;

/// Generated directories relative to the project root, in report order. Kept in one place so
/// a new scaffold output means one new line here (and its `.gitignore` rule in the template).
const ARTIFACT_DIRS: &[&str] = &[
    // Every `day build`/`launch`/`pack` output: per-target cargo dirs, xcodebuild SYMROOTs,
    // staged resources, jniLibs, screenshots, dist artifacts, SBOMs, generated xcconfig.
    "build",
    // Bare `cargo`/rust-analyzer builds (the mock default) — `day build` never writes here.
    "target",
    // Gradle (platform/android/.gitignore + the root ignore): the dependency/task caches and
    // the module build dirs. `local.properties` is machine config and stays.
    "platform/android/.gradle",
    "platform/android/build",
    "platform/android/app/build",
    "platform/android/app/.cxx",
    // hvigor (platform/harmony/.gitignore): caches, installed modules, module outputs, and
    // the ArkTS/resource staging the CLI regenerates into the scaffold every build (hvigor
    // compiles only from inside the module, which is why these are not under build/).
    "platform/harmony/.hvigor",
    "platform/harmony/oh_modules",
    "platform/harmony/entry/oh_modules",
    "platform/harmony/entry/build",
    "platform/harmony/entry/libs",
    "platform/harmony/entry/.preview",
    "platform/harmony/entry/src/main/resources/rawfile/day",
    "platform/harmony/entry/src/main/ets/daypieces",
    "platform/harmony/entry/src/main/ets/daybridge",
    "platform/harmony/entry/src/main/ets/day",
    "platform/harmony/entry/src/main/cpp/types/libentry",
    // xcodebuild intermediates land under the SYMROOT `day build` sets (inside build/), so
    // these exist only after an in-place `xcodebuild` without one — covered defensively.
    "platform/ios/build",
    "platform/macos/build",
    // The app's own SwiftPM package's local `swift test` scratch (docs/swiftui.md).
    "swiftui/.build",
];

/// Stop recorded sessions, then remove every artifact directory that exists. Returns the
/// bytes reclaimed (0 for a dry run, which only reports).
pub fn run(project: &Project, dry_run: bool) -> Result<u64, String> {
    // A live session holds its app's store and its entry in build/day/sessions.json — clean
    // under it and the runner is orphaned mid-run. Same teardown as `day stop --all`. A dry
    // run stops nothing: it must leave the project exactly as it found it.
    for session in crate::sessions::list(&project.root) {
        if dry_run {
            status("Would stop", &session.target);
            continue;
        }
        if let Ok(target) = crate::external::find_target(project, &session.target) {
            crate::script::terminate(project, target);
        }
        crate::sessions::remove(&project.root, &session.target);
        status("Stopped", &session.target);
    }

    let mut reclaimed = 0u64;
    let mut removed = 0u32;
    for rel in ARTIFACT_DIRS {
        let dir = project.root.join(rel);
        if !dir.is_dir() {
            continue;
        }
        let size = dir_size(&dir);
        if dry_run {
            status("Would remove", &format!("{rel} ({})", human_size(size)));
            removed += 1;
            continue;
        }
        std::fs::remove_dir_all(&dir).map_err(|e| format!("removing {rel}: {e}"))?;
        status("Removed", &format!("{rel} ({})", human_size(size)));
        reclaimed += size;
        removed += 1;
    }
    if removed == 0 {
        status("Clean", "nothing to remove — no build artifacts found");
    } else if dry_run {
        status(
            "Clean",
            &format!("dry run — {removed} director(ies) would go"),
        );
    } else {
        status(
            "Cleaned",
            &format!(
                "{removed} director(ies), {} reclaimed",
                human_size(reclaimed)
            ),
        );
    }
    Ok(reclaimed)
}

/// Recursive apparent size (file lengths, symlinks not followed). Unreadable entries count as
/// zero — a clean must not fail over a permission quirk in a directory it is about to delete.
fn dir_size(dir: &Path) -> u64 {
    let Ok(rd) = std::fs::read_dir(dir) else {
        return 0;
    };
    let mut total = 0u64;
    for entry in rd.flatten() {
        let Ok(meta) = entry.metadata() else {
            continue;
        };
        if meta.is_dir() {
            total += dir_size(&entry.path());
        } else {
            total += meta.len();
        }
    }
    total
}

/// `12.3 GiB`-style, one decimal, binary units — small enough to hand-roll (no new dependency
/// for a status line).
fn human_size(bytes: u64) -> String {
    const UNITS: &[&str] = &["B", "KiB", "MiB", "GiB", "TiB"];
    let mut value = bytes as f64;
    let mut unit = 0;
    while value >= 1024.0 && unit < UNITS.len() - 1 {
        value /= 1024.0;
        unit += 1;
    }
    if unit == 0 {
        format!("{bytes} B")
    } else {
        format!("{value:.1} {}", UNITS[unit])
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn sizes_read_in_binary_units() {
        assert_eq!(human_size(0), "0 B");
        assert_eq!(human_size(512), "512 B");
        assert_eq!(human_size(2048), "2.0 KiB");
        assert_eq!(human_size(5 * 1024 * 1024 + 300 * 1024), "5.3 MiB");
        assert_eq!(human_size(30 * 1024 * 1024 * 1024), "30.0 GiB");
    }

    #[test]
    fn dir_size_sums_nested_files() {
        let dir = std::env::temp_dir().join(format!("day-clean-size-{}", std::process::id()));
        let nested = dir.join("a/b");
        std::fs::create_dir_all(&nested).expect("mkdir");
        std::fs::write(dir.join("one"), vec![0u8; 100]).expect("write");
        std::fs::write(nested.join("two"), vec![0u8; 200]).expect("write");
        assert_eq!(dir_size(&dir), 300);
        let _ = std::fs::remove_dir_all(&dir);
    }
}
